---
Name: tinypngconfig
---
Image:
  extensions:
    - TinyPngImageExtension
Injector:
  Image:
    class: TinyPngImage
  Image_Cached:
    class: TinyPngImage_Cached
  TinyPngImage_Cached:
    class: TinyPngImage_Cached
